# archivo de configuración para GitHub Actions
# nombre del workflow
name: Deploy to GitHub Pages

# controles cuando el workflow corra
on:
  # Triggers cuando haya un push o una solicitud de pull request en la rama "main" 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Permite que el workflow se ejecute manualmente desde la pestaña de Actions en GitHub
  workflow_dispatch:


jobs:
  # Este workflow contiene un job llamado "deploy"
  deploy:
    # Este job se ejecutará en un runner con el sistema operativo Ubuntu (la última versión disponible)
    runs-on: ubuntu-latest

    # Tareas individuales que se ejecutaran en el job
    steps:
      # Clona el repositorio en el runner para que los siguientes steps tengan acceso al código
      - uses: actions/checkout@v4

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: .
          token: ${{ secrets.EXAMEN_PARCIAL }}

      # Ejecuta dos comandos echo en secuencia. El primer comando imprime "Add other actions to build," y el segundo imprime "test, and deploy your project." en la consola
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
